version: '3.1'
services:
  stats-server:
    build: stats/statservice
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
        - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistic
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:15-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
    - "6541:5432"
    environment:
    - POSTGRES_DB=statistic
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm_service_image
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    depends_on:
        - ewm-db
    environment:
      - EWM_STATS_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main_service
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:15-alpine
    container_name: ewm-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"

    environment:
      - POSTGRES_DB=main_service
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
